### ISSUE TITLE
Initial simulator

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/lilypad-simulator#1]
- [ ] list service providers e.g. show me all the solvers
- [ ] implement solver, resource provider & job creator APIs
- [ ] post a resource offer and job offer via the solver
- [ ] solver matches & broadcasts event back to listeners
- [ ] simulate resource provider timeout upon deal creation
```[tasklist]
### Tasks
- [ ] implement smart contract
```
